# Generated by Django 3.2.9 on 2021-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tweet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetresults',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
