# Generated by Django 3.2.9 on 2021-11-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tweetresults_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetresults',
            old_name='agressive',
            new_name='aggressive',
        ),
    ]
