# Generated by Django 3.1.3 on 2021-11-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usertweethistory_user'),
        ('app', '0006_auto_20211124_1749'),
    ]

    operations = [
    ]
