# Generated by Django 3.1.3 on 2021-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20211125_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweethistory',
            name='judgement',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Offensive', 'Offensive'), ('Aggressive', 'Aggressive'), ('Both', 'Both'), ('Skipped', 'Skip')], default='Neutral', max_length=20),
        ),
    ]
