# Generated by Django 3.2.9 on 2021-11-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211125_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetresults',
            name='aggressive',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tweetresults',
            name='offensive',
            field=models.FloatField(default=0),
        ),
    ]
